[package]
name = "socktrace"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
clap = { version = "4.5.58", features = ["derive", "env"] }
libc = "0.2.180"
nix = { version = "0.31.1", features = ["process", "ptrace", "signal", "uio"] }
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread", "sync"] }
